---
scope: postgres
namespace: /pg_cluster/
name: pg_node3
restapi:
  listen: 0.0.0.0:8008
  connect_address: pg_node3:8008
etcd3:
  hosts: etcd1:2379,etcd2:2379,etcd3:2379
retry_timeout: 60
loop_wait: 20
bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:
        wal_level: replica
        hot_standby: "on"
        max_wal_senders: 5
        max_replication_slots: 5
  initdb:
    - encoding: UTF8
    - data-checksums
  pg_hba:
    - host replication replicator 0.0.0.0/0 md5
    - host all all 0.0.0.0/0 md5
  users:
    admin:
      password: admin
      options:
        - createrole
        - createdb
postgresql:
  listen: 0.0.0.0:5432
  connect_address: pg_node3:5432
  data_dir: /var/lib/postgresql/data
  pgpass: /tmp/pgpass
  parameters:
    primary_conninfo: 'host=pg_node1 port=5432 user=replicator password=replicator'
  recovery_conf:
    restore_command: ''
  authentication:
    replication:
      username: replicator
      password: replicator
    superuser:
      username: postgres
      password: postgres
  use_slots: true
  parameters:
    max_replication_slots: 10
    wal_level: replica
    hot_standby: "on"
    max_wal_senders: 10
tags:
  nofailover: false
  noloadbalance: false
  clonefrom: false
  nosync: false
